name: Build Android APKs

on:
  push:
    branches:
      - main  # Change this to the main branch of your repository
      # - development

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.1'  # Adjust as needed

      - name: Get packages
        run: flutter pub get

      - name: Build APKs
        run: flutter build apk --split-per-abi
